[build]
  publish = "build"
  command = "npm ci && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  # Backend API URLs removed - using built-in data for stable deployment
  # REACT_APP_API_URL = "https://web-production-5f625.up.railway.app/api/products"
  # REACT_APP_API_BASE_URL = "https://web-production-5f625.up.railway.app"
  # REACT_APP_PRODUCTS_API_URL = "https://web-production-5f625.up.railway.app/api"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
